# #################################
# Basic training parameters for enhancement.
#
# Authors:
#  * Szu-Wei Fu 2020
#  * Chien-Feng Liao 2020
#  * Peter Plantinga 2020, 2021
# #################################

data_folder: ./data
xp_name: base_default
output_folder: !ref ./results/<xp_name>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: !ref <save_folder>/train.json
valid_annotation: !ref <save_folder>/valid.json
test_annotation: !ref <save_folder>/test.json
skip_prep: False

# whisper settings
text_normalizer: !new:whisper.normalizers.EnglishTextNormalizer
whisper_model: tiny

# Training Parameters
batch_size: 64
num_workers: 4
dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>
split: test
